sudo: false

language: ruby
rvm:
  - 2.1

os:
  - linux
  
env:
  global:
  # speeds up installing html-proofer
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 

script:
  - bundle install
  - bundle exec jekyll serve
  - bundle exec htmlproof ./_site --disable-external
