language: cpp

branches:
  except:
    - gh-pages

os:
  - linux

compiler:
  - clang
  - gcc

env:
  global:
    # Encrypted COVERITY_SCAN_TOKEN
    - secure: "M4RswpLBKVbIfY2k6W9mNFoSvJRpWFtMd5ynuMwgaBoaDbwn449KVfWKIlFruHGDfa9E/rB+y2twY5KktJm+RcLP8jvJCrWITy3E30rZQHAIgI1oAdy6i7NdMXHJYFQZs/eSYKZsN3/dfmzvnghA2txCG35tSxyLyb0vJp95VzY="

before_install:
  # GCC / Clang (Needed until Travis CI updates to Ubuntu 14.04+)
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  
  # Clang (Needed until Travis CI updates to Ubuntu 14.04+)
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  # CMake (Needed until Travis CI updates to Ubuntu 14.04+)
  - sudo add-apt-repository -y ppa:kalakris/cmake

  - sudo apt-get update -qq

install:
  # GCC
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq --force-yes g++-4.9; fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90; fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90; fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90; fi
  
  # Clang
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install -qq --force-yes g++-4.8; fi
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/clang-3.4 90; fi
  - if [ "$CXX" == "clang++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/clang++-3.4 90; fi
  
  # CMake (Needed until Travis CI updates to Ubuntu 14.04+)
  - sudo apt-get install -qq cmake
  
  # Armadillo C++
  - sudo apt-get install -qq libblas-dev
#  - sudo apt-get install -qq libopenblas-dev
  - sudo apt-get install -qq liblapack-dev
  - wget -O armadillo.tar.gz http://downloads.sourceforge.net/project/arma/armadillo-4.650.3.tar.gz
  - mkdir armadillo
  - tar -xzf armadillo.tar.gz -C ./armadillo --strip-components=1
  - cd armadillo
  - cmake .
  - make -j 4
  - sudo make install
  - cd ..
  - rm -Rf armadillo armadillo.tar.gz

  # Catch
  - wget -O catch.tar.gz https://github.com/philsquared/Catch/archive/3e0c5018123e7e32b3c35f4169cbdca4bcb8f332.tar.gz
  - mkdir catch
  - tar -xzf catch.tar.gz -C ./catch --strip-components=1
  - sudo cp -R catch/single_include/catch.hpp /usr/local/include/
  - rm -Rf catch catch.tar.gz
  
  # MPI (This will actually install 3.x on Ubuntu 14.04+ and 2.x on previous versions)
  - sudo apt-get install -qq libmpich2-dev
  
  # Cereal
  - wget -O cereal.tar.gz https://github.com/USCiLab/cereal/archive/v1.1.0.tar.gz
  - mkdir cereal
  - tar -xzf cereal.tar.gz -C ./cereal --strip-components=1
  - sudo cp -R cereal/include/cereal /usr/local/include/
  - rm -Rf cereal cereal.tar.gz

  # LCOV (Needed until Travis CI updates to Ubuntu 14.04+)
  - if [ "$CXX" == "g++" ]; then wget -O lcov.tar.gz https://github.com/linux-test-project/lcov/archive/v1.11.tar.gz; fi
  - if [ "$CXX" == "g++" ]; then mkdir lcov; fi
  - if [ "$CXX" == "g++" ]; then tar -xzf lcov.tar.gz -C ./lcov --strip-components=1; fi
  - if [ "$CXX" == "g++" ]; then cd lcov; fi
  - if [ "$CXX" == "g++" ]; then sudo make install; fi
  - if [ "$CXX" == "g++" ]; then cd ..; fi
  - if [ "$CXX" == "g++" ]; then rm -Rf lcov lcov.tar.gz; fi
#  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq lcov; fi

  # LCOV to Coveralls conversion + upload
  - if [ "$CXX" == "g++" ]; then gem install coveralls-lcov; fi
  
addons:
  coverity_scan:
    project:
      name: "SebastianNiemann/Mantella"
    notification_email: niemann@sra.uni-hannover.de
    build_command_prepend: "cov-configure --compiler gcc-4.8 --template; cmake -DBUILD_TESTS=On"
    build_command: "make -j 4"
    branch_pattern: coverity_scan

script:
  - if [ "$CXX" == "g++" ]; then cmake -DBUILD_TESTS=ON -DMEASURE_CODE_COVERAGE=On .; fi
  - if [ "$CXX" == "clang++" ]; then cmake -DBUILD_TESTS=ON -DSUPPORT_MPI=On .; fi
  - make -j 4
  - sudo make install
  
after_success:
  - if [ "$CXX" == "g++" ]; then cd ./CMakeFiles/libTest.dir/test/; fi
  - if [ "$CXX" == "g++" ]; then lcov --directory . --capture --output-file coverage.info; fi
  - if [ "$CXX" == "g++" ]; then lcov --remove coverage.info '/usr/*' --output-file coverage.info; fi
  - if [ "$CXX" == "g++" ]; then lcov --list coverage.info; fi
  - if [ "$CXX" == "g++" ]; then coveralls-lcov coverage.info; fi
