language: cpp

compiler:
# Skipped until Travis CI updates to Ubuntu 14.04+
#  - clang
  - gcc

env:
  global:
   # Encrypted COVERITY_SCAN_TOKEN
   - secure: "M4RswpLBKVbIfY2k6W9mNFoSvJRpWFtMd5ynuMwgaBoaDbwn449KVfWKIlFruHGDfa9E/rB+y2twY5KktJm+RcLP8jvJCrWITy3E30rZQHAIgI1oAdy6i7NdMXHJYFQZs/eSYKZsN3/dfmzvnghA2txCG35tSxyLyb0vJp95VzY="

before_install:
  # GCC
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # Needed until Travis CI updates to Ubuntu 14.04+
  # Boost (filesystem)
  - sudo add-apt-repository -y ppa:boost-latest/ppa

  - sudo apt-get update -qq

install:
  # GCC
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq --force-yes g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  
  # CMake (Needed until Travis CI updates to Ubuntu 14.04+)
  - wget -O cmake.tar.gz http://www.cmake.org/files/v3.0/cmake-3.0.2.tar.gz
  - mkdir cmake
  - tar -xzf cmake.tar.gz -C ./cmake --strip-components=1
  - cd cmake
  - ./bootstrap
  - make
  - sudo make install
  - cd ..
  - rm -Rf cmake cmake.tar.gz
  
  # MPI (this will actually install 3.x on Ubuntu 14.04+ and 2.x on previous versions)
  - sudo apt-get install -qq libmpich2-dev
  
  # Armadillo C++
  - sudo apt-get install -qq libopenblas-dev
  - sudo apt-get install -qq liblapack-dev
  - wget -O armadillo.tar.gz http://downloads.sourceforge.net/project/arma/armadillo-4.600.0.tar.gz
  - mkdir armadillo
  - tar -xzf armadillo.tar.gz -C ./armadillo --strip-components=1
  - cd armadillo
  - cmake .
  - make
  - sudo make install
  - cd ..
  - rm -Rf armadillo armadillo.tar.gz

  # Cereal
  - wget -O cereal.tar.gz https://github.com/USCiLab/cereal/archive/v1.0.0.tar.gz
  - mkdir cereal
  - tar -xzf cereal.tar.gz -C ./cereal --strip-components=1
  - sudo cp -R cereal/include/cereal /usr/local/include/
  - rm -Rf cereal cereal.tar.gz

  # Catch
  # Needed until Travis CI updates to Ubuntu 14.04+
  - wget -O catch.tar.gz https://github.com/philsquared/Catch/archive/3e0c5018123e7e32b3c35f4169cbdca4bcb8f332.tar.gz
  - mkdir catch
  - tar -xzf catch.tar.gz -C ./catch --strip-components=1
  - sudo cp -R catch/single_include/catch.hpp /usr/local/include/
  - rm -Rf catch catch.tar.gz
#  - sudo apt-get install -qq catch  

  # Boost (filesystem)
  # Needed until Travis CI updates to Ubuntu 14.04+
  - sudo apt-get install -qq libboost-filesystem1.54-dev
#  - sudo apt-get install -qq libboost-filesystem-

  # LCOV
  # Needed until Travis CI updates to Ubuntu 14.04+
  - if [ "$CXX" = "g++-4.8" ]; then wget -O lcov.tar.gz http://downloads.sourceforge.net/ltp/lcov-1.11.tar.gz; fi
  - if [ "$CXX" = "g++-4.8" ]; then mkdir lcov; fi
  - if [ "$CXX" = "g++-4.8" ]; then tar -xzf lcov.tar.gz -C ./lcov --strip-components=1; fi
  - if [ "$CXX" = "g++-4.8" ]; then cd lcov; fi
  - if [ "$CXX" = "g++-4.8" ]; then sudo make install; fi
  - if [ "$CXX" = "g++-4.8" ]; then cd ..; fi
  - if [ "$CXX" = "g++-4.8" ]; then rm -Rf lcov lcov.tar.gz; fi
#  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq lcov; fi

  # LCOV to Coveralls conversion + upload
  - if [ "$CXX" = "g++-4.8" ]; then gem install coveralls-lcov; fi
  
addons:
  coverity_scan:
    project:
      name: "SebastianNiemann/Mantella"
    notification_email: niemann@sra.uni-hannover.de
    build_command_prepend: "cov-configure --compiler gcc-4.8 --template; cmake -DBUILD_ALL=on ."
    build_command: "make"
    branch_pattern: coverity_scan

script: 
  - if [ "$CXX" == "g++-4.8" ]; then cmake -DBUILD_ALL=On -DMEASURE_CODE_COVERAGE=On .; fi
  - if [ "$CXX" == "clang++" ]; then cmake -DBUILD_ALL=On .; fi
  - make
  - sudo make install
  
after_success:
  - if [ "$CXX" == "g++-4.8" ]; then cd ./CMakeFiles/libTest.dir/test/; fi
  - if [ "$CXX" == "g++-4.8" ]; then lcov --directory . --capture --output-file coverage.info; fi
  - if [ "$CXX" == "g++-4.8" ]; then lcov --remove coverage.info '/usr/*' --output-file coverage.info; fi
  - if [ "$CXX" == "g++-4.8" ]; then lcov --list coverage.info; fi
  - if [ "$CXX" == "g++-4.8" ]; then coveralls-lcov coverage.info; fi

