title: Mantella
description: Mantella is an efficiency-focused, modern C++ library for analysing and solving optimisation problems.

github: https://github.com/SebastianNiemann/Mantella

# Avoids .html suffixes
permalink: pretty

markdown: kramdown
kramdown: 
  input: GFM
  parse_block_html: true
  hard_wrap: false
highlighter: rouge

error_mode: :strict
exclude: [vendor]

array: []