# Site settings
baseurl: http://mantella.info

# Note, it is not required for the title to match the project name
title: Mantella
subtitle: An efficiency-focused, modern C++ library for analysing and solving optimisation problems.
description: Mantella is an efficiency-focused, modern C++ library for analysing and solving optimisation problems.
author: Core Mantella team
  
project_name: Mantella
github-url: https://github.com/SebastianNiemann/Mantella

navigation:
 - Get Started
 - API Reference
 - License
 - Questions
 
api_version:
 - 1.x
 - Draft

# Avoids the need of .html suffixes
permalink: pretty
  
# Parse Markdown inside HTML blocks
kramdown:
  parse_block_html: true

# Provide SASS files as compressed CSS files
sass:
  sass_dir: _sass
  style: :compressed
